sudo: false
language: php

php:
    - 7.3
    - 7.4
    - nightly
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    - composer self-update --2
    - composer install --prefer-dist --no-interaction --ignore-platform-req=php

script: vendor/bin/phpunit --coverage-text
